[package]
name = "mercurial-vault"
version = "0.4.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "mercurial_vault"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []
test-bpf = []
devnet = []
no-capture = []

[dependencies]
serde = { version = "1.0.136"}
anchor-lang = "0.24.2"
anchor-spl = "0.24.2" 
port-variable-rate-lending-instructions = "0.3.*"
port-staking-instructions = "0.2.*"
solana-program = "1.9.*"
spl-token = { version = "3.1.1", features = ["no-entrypoint"] }
